from django.conf.urls.defaults import patterns

urlpatterns = patterns('',
    (r'^facebook/$', 'sns.chan.views.facebook_list'),
    (r'^fbpage/$', 'sns.chan.views.fbpage_list'),
    (r'^$', 'sns.chan.views.list'),
    (r'^fanpage/$', 'sns.chan.views.fanpage_list'),
    (r'^fanpage/refresh/$', 'sns.chan.views.fanpage_refresh'),
    (r'^groupmember/$', 'sns.chan.views.groupmember_list'),
    (r'^groupmember/refresh/$', 'sns.chan.views.groupmember_refresh'),
    (r'^groupmember/sync/$', 'sns.chan.views.groupmember_sync'),
    (r'^conversation/$', 'sns.chan.views.conversationDetails'),
    (r'^delete/$', 'sns.chan.views.delete'),
    (r'^details/$', 'sns.chan.views.details'),
    (r'^details/dm_inbox$', 'sns.chan.views.details_dm_inbox'),  
    (r'^details/dm_outbox$', 'sns.chan.views.details_dm_outbox'),  
    (r'^details/mentions$', 'sns.chan.views.details_mentions'),
    (r'^details/followers$', 'sns.chan.views.details_my_followers'),
    (r'^details/friends$', 'sns.chan.views.details_my_friends'),
    (r'^details/friends/unfollow_him$', 'sns.chan.views.unFollowMyFriends'),    
    (r'^details/friends/follow_him$', 'sns.chan.views.FollowFriends'),
    (r'^details/sent_tweets$', 'sns.chan.views.details_sent_tweets'),
    (r'^details/home_tweets$', 'sns.chan.views.details_home_tweets'),
    (r'^details/favorites$', 'sns.chan.views.details_favorites'),
    (r'^details/dm/delete$', 'sns.chan.views.deleteDM'),     
    #(r'^details/dm/reply$', 'sns.chan.views.replyDM'), 
    (r'^details/dm/send$', 'sns.chan.views.sendDM'),   
    (r'^details/tweets/delete$', 'sns.chan.views.deleteTweets'),
    (r'^details/tweets/reply$', 'sns.chan.views.replyTweets'),
    (r'^details/retweets_by_others$', 'sns.chan.views.retweets_by_others'),
    (r'^details/retweets_by_you$', 'sns.chan.views.retweets_by_you'),
    (r'^details/your_tweets_retweeted$', 'sns.chan.views.your_tweets_retweeted'),
    (r'^details/tweets/retweet$', 'sns.chan.views.Retweets'),
    (r'^details/favorites/create$', 'sns.chan.views.favorite_create'),
    (r'^details/favorites/delete$', 'sns.chan.views.deleteFavorite'),    
    (r'^twitter/login$', 'sns.chan.views.twitter_login'),
    (r'^twitter/sync$', 'sns.chan.views.twitter_sync'), 
    (r'^twitter/callback$', 'sns.chan.views.twitter_callback'),
    (r'^twitter/confirm$', 'sns.chan.views.twitter_confirm'),
    (r'^twitter/export/$', 'sns.chan.views.twitter_export'),
    (r'^facebook/login$', 'sns.chan.views.facebook_login'),
    (r'^facebook/callback$', 'sns.chan.views.facebook_callback'),
    (r'^facebook/account/confirm$', 'sns.chan.views.fb_account_confirm'),    
    (r'^facebook/sync$', 'sns.chan.views.facebook_sync'), 
    (r'^facebook/delete/$', 'sns.chan.views.facebook_delete'),
    (r'^facebook/group/change/$', 'sns.chan.views.facebook_group_change'),
    (r'^facebook/page/change/$', 'sns.chan.views.facebook_page_change'),
    (r'^fbpage/login$', 'sns.chan.views.fbpage_login'),
    (r'^fbpage/add$', 'sns.chan.views.fbpage_add'),
    (r'^fbpage/delete/$', 'sns.chan.views.fbpage_delete'),
    (r'^fbpage/sync/$', 'sns.chan.views.fbpage_sync'),

    (r'^twitter/suspended$', 'sns.chan.views.twitter_suspended_list'),
    (r'^twitter/restored$', 'sns.chan.views.twitter_restored_list'),
    (r'^twitter/suspended/export$', 'sns.chan.views.twitter_suspended_export'),
)