
USER_OBJ_LIST_POSTS = 0
USER_OBJ_LIST_RATINGS = 1
USER_OBJ_LIST_COMMENTS = 2
USER_OBJ_LIST_FOLLOWING_POSTS = 3
USER_OBJ_LIST_FOLLOWING_TOPICS = 4
USER_OBJ_LIST_FOLLOWING_USERS = 5

USER_OBJ_LIST_MAP = {
    USER_OBJ_LIST_POSTS : "Posts",
    USER_OBJ_LIST_RATINGS : "Ratings",
    USER_OBJ_LIST_COMMENTS : "Comments",
#    USER_OBJ_LIST_FOLLOWING_POSTS : "FollowingPosts",
    }

USER_OBJ_LISTS = USER_OBJ_LIST_MAP.keys()

