from django.conf.urls.defaults import patterns
urlpatterns = patterns('',
    (r'^rule/article/$', 'sns.post.views.articlerule_list'),
    (r'^rule/check/$', 'sns.post.views.postingrule_check'),
    (r'^rule/article/create/$', 'sns.post.views.articlerule_create'),
    (r'^rule/article/quickcreate/$', 'sns.post.views.quickarticlerule_create'),
    (r'^rule/article/quickcheck/$', 'sns.post.views.quickarticlerule_check'),
    (r'^rule/article/getLink/$', 'sns.post.views.quickarticlerule_link'),
    (r'^rule/article/detail/(.*)$', 'sns.post.views.articlerule_detail'),
    (r'^rule/article/activate/$', 'sns.post.views.articlerule_activate'),
    (r'^rule/article/deactivate/$', 'sns.post.views.articlerule_deactivate'),
    (r'^rule/article/update/$', 'sns.post.views.articlerule_update'),
    (r'^rule/article/delete/$', 'sns.post.views.articlerule_delete'),
    (r'^rule/article/edit/$', 'sns.post.views.articlerule_edit'),
    (r'^rule/feed/$', 'sns.post.views.feedrule_list'),
    (r'^rule/feed/create/$', 'sns.post.views.feedrule_create'),
    (r'^rule/feed/detail/(.*)$', 'sns.post.views.feedrule_detail'),
    (r'^rule/feed/activate/$', 'sns.post.views.feedrule_activate'),
    (r'^rule/feed/deactivate/$', 'sns.post.views.feedrule_deactivate'),
    (r'^rule/feed/update/$', 'sns.post.views.feedrule_update'),
    (r'^rule/feed/delete/$', 'sns.post.views.feedrule_delete'),
    (r'^rule/feed/quickcreate/$', 'sns.post.views.quickfeedrule_create'),
    (r'^rule/feed/edit/$', 'sns.post.views.feedrule_edit'),
    (r'^posting/(?P<ruleid>.*)$', 'sns.post.views.posting_list'),
    (r'^post/(?P<postingid>.*)$', 'sns.post.views.post_list'),

)