from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^rule/$', 'sns.dm.views.dmrule_list'),
    (r'^rule/create/$', 'sns.dm.views.dmrule_create'),
    (r'^rule/activate/$', 'sns.dm.views.dmrule_activate'),
    (r'^rule/deactivate/$', 'sns.dm.views.dmrule_deactivate'),
    (r'^rule/update/$', 'sns.dm.views.dmrule_update'),
    (r'^rule/delete/$', 'sns.dm.views.dmrule_delete'),
    (r'^rule/chart/$', 'sns.dm.views.dmrule_chart'),
    (r'^rule/chartdetail/$', 'sns.dm.views.dmrule_chartdetail'),
    (r'^chartpath/rule/chartdata/$', 'sns.dm.views.dmrule_chartdata'), 
    (r'^rule/sendcount/$', 'sns.dm.views.dmrule_sendcount'),
    (r'^rule/clickcount/$', 'sns.dm.views.dmrule_clickcount'),
    (r'^all/rule/list/$', 'sns.dm.views.dm_all_rule_list'),
    (r'^rule/advanced/$', 'sns.dm.views.dmrule_advanced_list'),
    (r'^rule/advanced/create/$', 'sns.dm.views.dmrule_advanced_create'),
    (r'^rule/advanced/activate/$', 'sns.dm.views.dmrule_advanced_activate'),
    (r'^rule/advanced/deactivate/$', 'sns.dm.views.dmrule_advanced_deactivate'),
    (r'^rule/advanced/update/$', 'sns.dm.views.dmrule_advanced_update'),
    (r'^rule/advanced/delete/$', 'sns.dm.views.dmrule_advanced_delete'),
    (r'^rule/advanced/sync/$', 'sns.dm.views.dmrule_advanced_sync'),
    (r'^rule/advanced/confirm/$', 'sns.dm.views.dmrule_advanced_confirm'),
    (r'^rule/advanced/chart/$', 'sns.dm.views.dmrule_advanced_chart'),
)