SHOW_SEARCH_NUMBER = 10
LIST_ORDER = [('asc','Ascending') , ('desc','Descending')]
LIST_PAGINATE = [('50','50') , ('100','100')]
DEFAULT_INITIAL_PAGE_SIZE = 50
CONV_MGMT_PAGE_SIZE = 20
TEXT_SUFFIX_LENGTH = 3

