""" All system load, performance tuning, and other limits go here. """

LIMIT_POST_DAILY_PER_USER = 2000
LIMIT_POST_DAILY_ADMIN = 2000
LIMIT_EXECUTION_DAILY_PER_USER = 2000
LIMIT_CHANNEL_ADD_PER_USER = 1000
LIMIT_FEED_ADD_PER_USER = 1000
LIMIT_FEEDRULE_ADD_PER_USER = 1000
LIMIT_ARTICLE_ADD_PER_USER = 1000
LIMIT_ARTICLERULE_ADD_PER_USER = 1000
