from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^account/$', 'fe.follow.views.followacctrule_list'),
    (r'^account/create/$', 'fe.follow.views.followacctrule_create'),
    (r'^account/update/$', 'fe.follow.views.followacctrule_update'),
    (r'^account/delete/$', 'fe.follow.views.followacctrule_delete'),
    (r'^account/delete/admin/$', 'fe.follow.views.followacctrule_admin_delete'),
    (r'^account/chart/$', 'fe.follow.views.followacctrule_chart'),
    (r'^account/chartdetail$', 'fe.follow.views.followacctrule_chartdetail'),
    (r'^account/detail/(.*)$', 'fe.follow.views.followacctrule_detail'),
    (r'^account/activate/$', 'fe.follow.views.followacctrule_activate'),
    (r'^account/deactivate/$', 'fe.follow.views.followacctrule_deactivate'),
    (r'^account/check/$', 'fe.follow.views.sourceAccountCheck'),
    (r'^account/safelist/$', 'fe.follow.views.sourceAccountSafeList'),
    (r'^account/safelist/change$', 'fe.follow.views.sourceAccountSafeListChange'),
    (r'^account/safelist/help/$', 'fe.follow.views.sourceAccountSafeListHelp'),
    (r'^account/status/$', 'fe.follow.views.update_channel_status'),
    (r'^chartpath/account/chartdata/$', 'fe.follow.views.followacctrule_chartdata'),
    (r'^all/rule/list/$', 'fe.follow.views.all_rule_list'),
    (r'^suspend/rule/list/$', 'fe.follow.views.suspended_followrule'),
    (r'^system/$', 'fe.follow.views.config_main'),
    (r'^account/config/toggle/$', 'fe.follow.views.config_toggle'),
    (r'^account/config/update/$', 'fe.follow.views.config_update'),
    (r'^account/config/reset/$', 'fe.follow.views.config_reset'),
    (r'^account/reactivate_protected/$', 'fe.follow.views.reactivate_protected'),
    (r'^account/reactivate_suspended/$', 'fe.follow.views.reactivate_suspended'),
)

