TARGET_STATE_NORMAL = 0
TARGET_STATE_ERROR  = 1
TARGET_STATES = range(2)


MONITOR_TARGET_FOLLOWER_ALLOC_LOG_CURSOR = 'monitor_tgtflwr_alloc_log_cursor' #datetime
MONITOR_TARGET_FOLLOWER_FOLLOW_LOG_CURSOR = 'monitor_tgtflwr_follow_log_cursor' #datetime

TARGET_FOLLOWERS_ALLOC_SIZE = 100
