DIVISIONS = [
     {
      "id": "abbotsford",
      "name": "Abbotsford",
      "country": "Canada",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 49.0568,
      "lng": -122.285,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "abilene",
      "name": "Abilene, TX",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 32.4487,
      "lng": -99.7331,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "akron-canton",
      "name": "Akron/Canton",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.0814,
      "lng": -81.519,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "albany-capital-region",
      "name": "Albany / Capital Region",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.6526,
      "lng": -73.7562,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "albuquerque",
      "name": "Albuquerque",
      "country": "USA",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 35.0845,
      "lng": -106.651,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "allentown-reading",
      "name": "Allentown / Reading",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 40.6084,
      "lng": -75.4902,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "amarillo",
      "name": "Amarillo",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 35.222,
      "lng": -101.831,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "anchorage",
      "name": "Anchorage",
      "country": "USA",
      "timezone": "Alaska",
      "timezoneOffsetInSeconds": -32400,
      "lat": 61.2181,
      "lng": -149.9,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "ann-arbor",
      "name": "Ann Arbor",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.2814,
      "lng": -83.7483,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "appleton",
      "name": "Appleton",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 44.2619,
      "lng": -88.4154,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "asheville",
      "name": "Asheville",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 35.6009,
      "lng": -82.554,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "athens-ga",
      "name": "Athens, GA",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 33.9558,
      "lng": -83.3824,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "atlanta",
      "name": "Atlanta",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 33.7545,
      "lng": -84.3897,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "augusta",
      "name": "Augusta",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 33.4742,
      "lng": -82.0097,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "austin",
      "name": "Austin",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 30.2687,
      "lng": -97.7452,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "bakersfield",
      "name": "Bakersfield",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 35.3733,
      "lng": -119.019,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "baltimore",
      "name": "Baltimore",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 39.2943,
      "lng": -76.6143,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "barrie",
      "name": "Barrie",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 44.3812,
      "lng": -79.687,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "baton-rouge",
      "name": "Baton Rouge",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 30.4507,
      "lng": -91.1545,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "billings",
      "name": "Billings",
      "country": "USA",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 45.7833,
      "lng": -108.501,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "birmingham",
      "name": "Birmingham",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 33.5207,
      "lng": -86.8025,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "boise",
      "name": "Boise",
      "country": "USA",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 43.6137,
      "lng": -116.238,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "boston",
      "name": "Boston",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.3589,
      "lng": -71.0578,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "buffalo",
      "name": "Buffalo",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.8864,
      "lng": -78.8784,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "calgary",
      "name": "Calgary",
      "country": "Canada",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 51.045,
      "lng": -114.057,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "cedar-rapids-iowa-city",
      "name": "Cedar Rapids / Iowa City",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 41.9625,
      "lng": -91.6918,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "central-jersey",
      "name": "Central Jersey",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 40.2171,
      "lng": -74.7429,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "charleston",
      "name": "Charleston",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 32.7766,
      "lng": -79.9309,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "charlotte",
      "name": "Charlotte",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 35.2314,
      "lng": -80.8458,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "chattanooga",
      "name": "Chattanooga",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 35.0456,
      "lng": -85.3097,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "chicago",
      "name": "Chicago",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 41.8795,
      "lng": -87.6243,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "cincinnati",
      "name": "Cincinnati",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 39.148,
      "lng": -84.477,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "cleveland",
      "name": "Cleveland",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.4995,
      "lng": -81.6954,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "colorado-springs",
      "name": "Colorado Springs",
      "country": "USA",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 38.8339,
      "lng": -104.821,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "columbia",
      "name": "Columbia",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 34.0007,
      "lng": -81.0348,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "columbia-mo",
      "name": "Columbia, MO",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 38.9481,
      "lng": -92.3268,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "columbus",
      "name": "Columbus",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 39.9612,
      "lng": -82.9988,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "columbus-ga",
      "name": "Columbus GA",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 32.461,
      "lng": -84.9877,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "corpus-christi",
      "name": "Corpus Christi",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 27.8006,
      "lng": -97.3964,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "dallas",
      "name": "Dallas",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 32.7811,
      "lng": -96.7971,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "dayton",
      "name": "Dayton",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 39.7589,
      "lng": -84.1916,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "daytona-beach",
      "name": "Daytona Beach",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 29.1988,
      "lng": -81.089,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "denver",
      "name": "Denver",
      "country": "USA",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 39.7551,
      "lng": -104.988,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "des-moines",
      "name": "Des Moines",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 41.6005,
      "lng": -93.6091,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "detroit",
      "name": "Detroit",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.3314,
      "lng": -83.0458,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "edmonton",
      "name": "Edmonton",
      "country": "Canada",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 53.5436,
      "lng": -113.49,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "el-paso",
      "name": "El Paso",
      "country": "USA",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 31.7587,
      "lng": -106.487,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "erie",
      "name": "Erie",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.1292,
      "lng": -80.0851,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "eugene",
      "name": "Eugene",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 44.0521,
      "lng": -123.087,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "evansville",
      "name": "Evansville",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 37.9748,
      "lng": -87.5558,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "fairfield-county",
      "name": "Fairfield County",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.3802,
      "lng": -73.4553,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "fayetteville",
      "name": "Fayetteville",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 35.0527,
      "lng": -78.8784,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "fort-lauderdale",
      "name": "Fort Lauderdale",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 26.1223,
      "lng": -80.1434,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "fort-myers-cape-coral",
      "name": "Fort Myers / Cape Coral",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 26.6406,
      "lng": -81.8723,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "fort-wayne",
      "name": "Fort Wayne",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.1306,
      "lng": -85.1289,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "fort-worth",
      "name": "Fort Worth",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 32.7254,
      "lng": -97.3208,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "fresno",
      "name": "Fresno",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 36.7477,
      "lng": -119.772,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "gainesville",
      "name": "Gainesville",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 29.6516,
      "lng": -82.3248,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "grand-rapids",
      "name": "Grand Rapids",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.9634,
      "lng": -85.6681,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "green-bay",
      "name": "Green Bay",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 44.5192,
      "lng": -88.0198,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "greenville",
      "name": "Greenville",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 34.8526,
      "lng": -82.394,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "halifax",
      "name": "Halifax",
      "country": "Canada",
      "timezone": "Atlantic Time (Canada)",
      "timezoneOffsetInSeconds": -14400,
      "lat": 44.6489,
      "lng": -63.5753,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "hampton-roads",
      "name": "Hampton Roads",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 36.8529,
      "lng": -75.978,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "harrisburg",
      "name": "Harrisburg",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 40.2737,
      "lng": -76.8844,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "hartford",
      "name": "Hartford",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.7637,
      "lng": -72.6851,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "honolulu",
      "name": "Honolulu",
      "country": "USA",
      "timezone": "Hawaii",
      "timezoneOffsetInSeconds": -36000,
      "lat": 21.3069,
      "lng": -157.858,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "houston",
      "name": "Houston",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 29.76,
      "lng": -95.3625,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "huntsville",
      "name": "Huntsville",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 34.7304,
      "lng": -86.5861,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "indianapolis",
      "name": "Indianapolis",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 39.767,
      "lng": -86.1563,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "inland-empire",
      "name": "Inland Empire",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 34.1083,
      "lng": -117.29,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "jackson",
      "name": "Jackson",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 32.2988,
      "lng": -90.1848,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "jacksonville",
      "name": "Jacksonville",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 30.3322,
      "lng": -81.6556,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "kalamazoo",
      "name": "Kalamazoo",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.2917,
      "lng": -85.5872,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "kansas-city",
      "name": "Kansas City",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 39.0997,
      "lng": -94.5786,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "kelowna",
      "name": "Kelowna",
      "country": "Canada",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 49.8799,
      "lng": -119.45,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "kingston",
      "name": "Kingston",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 44.2636,
      "lng": -76.5034,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "kitchener-waterloo",
      "name": "Kitchener - Waterloo",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 43.4343,
      "lng": -80.4777,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "knoxville",
      "name": "Knoxville",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 35.9606,
      "lng": -83.9207,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "lakeland",
      "name": "Lakeland",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 28.0395,
      "lng": -81.9498,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "lansing",
      "name": "Lansing",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.7325,
      "lng": -84.5555,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "las-vegas",
      "name": "Las Vegas",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 36.1146,
      "lng": -115.173,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "lexington",
      "name": "Lexington",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 38.0317,
      "lng": -84.4951,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "lincoln",
      "name": "Lincoln",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 40.8069,
      "lng": -96.6817,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "little-rock",
      "name": "Little Rock",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 34.7465,
      "lng": -92.2896,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "london",
      "name": "London, ON",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.9794,
      "lng": -81.2461,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "long-island",
      "name": "Long Island",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 40.8168,
      "lng": -73.0661,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "los-angeles",
      "name": "Los Angeles",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 34.0522,
      "lng": -118.243,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  [
         {
          "id": "los-angeles",
          "name": "Los Angeles",
          "lat": 34.0305,
          "lng": -118.318
        },
         {
          "id": "san-gabriel-valley",
          "name": "San Gabriel Valley",
          "lat": 34.0745,
          "lng": -118.011
        },
         {
          "id": "san-fernando-valley",
          "name": "San Fernando Valley",
          "lat": 34.2221,
          "lng": -118.446
        }
      ]
    },
     {
      "id": "louisville",
      "name": "Louisville",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 38.2542,
      "lng": -85.7594,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "lubbock",
      "name": "Lubbock",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 33.5779,
      "lng": -101.855,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "macon",
      "name": "Macon",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 32.8407,
      "lng": -83.6324,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "madison",
      "name": "Madison",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 43.0731,
      "lng": -89.4012,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "memphis",
      "name": "Memphis",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 35.1495,
      "lng": -90.049,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "miami",
      "name": "Miami",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 25.7743,
      "lng": -80.1903,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "midland-odessa",
      "name": "Midland / Odessa",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 31.9727,
      "lng": -102.392,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "milwaukee",
      "name": "Milwaukee",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 43.0389,
      "lng": -87.9065,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "minneapolis-stpaul",
      "name": "Minneapolis / St Paul",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 44.98,
      "lng": -93.2638,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "mobile-baldwin-county",
      "name": "Mobile / Baldwin County",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 30.6944,
      "lng": -88.0431,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "modesto",
      "name": "Modesto",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 37.6391,
      "lng": -120.997,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "montgomery",
      "name": "Montgomery",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 32.3668,
      "lng": -86.3,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "napa-sonoma",
      "name": "Napa / Sonoma",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 38.4405,
      "lng": -122.714,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "naples",
      "name": "Naples",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 26.142,
      "lng": -81.7948,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "nashville",
      "name": "Nashville",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 36.1659,
      "lng": -86.7844,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "new-orleans",
      "name": "New Orleans",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 29.9546,
      "lng": -90.0751,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "new-york",
      "name": "New York City",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 40.7561,
      "lng": -73.987,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "north-jersey",
      "name": "North Jersey",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 40.9598,
      "lng": -74.2219,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "ocala",
      "name": "Ocala",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 29.1872,
      "lng": -82.1401,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "ogden",
      "name": "Ogden",
      "country": "USA",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 41.223,
      "lng": -111.974,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "oklahoma-city",
      "name": "Oklahoma City",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 35.4676,
      "lng": -97.5164,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "omaha",
      "name": "Omaha",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 41.254,
      "lng": -95.9993,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "orange-county",
      "name": "Orange County",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 33.7456,
      "lng": -117.868,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "orlando",
      "name": "Orlando",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 28.5383,
      "lng": -81.3792,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "ottawa",
      "name": "Ottawa",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 45.4116,
      "lng": -75.6982,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "palm-beach",
      "name": "Palm Beach",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 26.7056,
      "lng": -80.0364,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "pensacola",
      "name": "Pensacola",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 30.4213,
      "lng": -87.2169,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "philadelphia",
      "name": "Philadelphia",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 39.9516,
      "lng": -75.1638,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "phoenix",
      "name": "Phoenix",
      "country": "USA",
      "timezone": "Arizona",
      "timezoneOffsetInSeconds": -25200,
      "lat": 33.4483,
      "lng": -112.074,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "piedmont-triad",
      "name": "Piedmont Triad",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 36.0726,
      "lng": -79.792,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "pittsburgh",
      "name": "Pittsburgh",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 40.4406,
      "lng": -79.9959,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "portland",
      "name": "Portland",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 45.5235,
      "lng": -122.676,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "portland-me",
      "name": "Portland, ME",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 43.6615,
      "lng": -70.2553,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "providence",
      "name": "Providence",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.824,
      "lng": -71.4128,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "raleigh-durham",
      "name": "Raleigh / Durham",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 35.7721,
      "lng": -78.6386,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "regina",
      "name": "Regina",
      "country": "Canada",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 50.45,
      "lng": -104.61,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "reno",
      "name": "Reno",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 39.5296,
      "lng": -119.814,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "richmond",
      "name": "Richmond",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 37.533,
      "lng": -77.467,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "rio-grande-valley",
      "name": "Rio Grande Valley",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 26.2034,
      "lng": -98.23,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "roanoke",
      "name": "Roanoke",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 37.271,
      "lng": -79.9414,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "rochester",
      "name": "Rochester",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 43.1548,
      "lng": -77.6156,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "rockford",
      "name": "Rockford",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 42.2711,
      "lng": -89.094,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "sacramento",
      "name": "Sacramento",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 38.5816,
      "lng": -121.494,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "salem-or",
      "name": "Salem OR",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 44.9429,
      "lng": -123.035,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "salt-lake-city",
      "name": "Salt Lake City",
      "country": "USA",
      "timezone": "Mountain Time (US & Canada)",
      "timezoneOffsetInSeconds": -25200,
      "lat": 40.7608,
      "lng": -111.891,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "san-angelo",
      "name": "San Angelo",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 31.4406,
      "lng": -100.452,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "san-antonio",
      "name": "San Antonio",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 29.4241,
      "lng": -98.4936,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "san-diego",
      "name": "San Diego",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 32.7188,
      "lng": -117.164,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "san-francisco",
      "name": "San Francisco",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 37.7752,
      "lng": -122.419,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  [
         {
          "id": "san-francisco",
          "name": "San Francisco",
          "lat": 37.7808,
          "lng": -122.418
        },
         {
          "id": "east-bay",
          "name": "East Bay",
          "lat": 37.8151,
          "lng": -122.24
        }
      ]
    },
     {
      "id": "san-jose",
      "name": "San Jose",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 37.3394,
      "lng": -121.895,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "santa-barbara",
      "name": "Santa Barbara",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 34.3996,
      "lng": -119.713,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "santa-clarita",
      "name": "Santa Clarita",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 34.3917,
      "lng": -118.543,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "santa-cruz",
      "name": "Santa Cruz",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 36.9741,
      "lng": -122.031,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "saskatoon",
      "name": "Saskatoon",
      "country": "Canada",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 52.1344,
      "lng": -106.648,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "savannah-hilton-head",
      "name": "Savannah/Hilton Head",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 32.0835,
      "lng": -81.0998,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "seattle",
      "name": "Seattle",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 47.621,
      "lng": -122.347,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  [
         {
          "id": "tacoma",
          "name": "Tacoma",
          "lat": 47.249,
          "lng": -122.465
        },
         {
          "id": "seattle",
          "name": "Seattle",
          "lat": 47.6113,
          "lng": -122.333
        }
      ]
    },
     {
      "id": "shreveport-bossier",
      "name": "Shreveport/Bossier",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 32.5252,
      "lng": -93.7502,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "sioux-falls",
      "name": "Sioux Falls",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 43.55,
      "lng": -96.7003,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "south-bend",
      "name": "South Bend",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.6834,
      "lng": -86.25,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "albany-ga",
      "name": "Southern Georgia",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 31.5785,
      "lng": -84.1557,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "spokane-coeur-dalene",
      "name": "Spokane / Coeur d'Alene",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 47.6588,
      "lng": -117.426,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "springfield-mo",
      "name": "Springfield MO",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 37.2153,
      "lng": -93.2982,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "springfield-ma",
      "name": "Springfield, MA",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.1015,
      "lng": -72.5898,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "stcatharines-niagara",
      "name": "St Catharines-Niagara",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 43.588,
      "lng": -77.7452,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "st-johns",
      "name": "St John's",
      "country": "Canada",
      "timezone": "Newfoundland",
      "timezoneOffsetInSeconds": -12600,
      "lat": 47.5615,
      "lng": -52.7127,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "stlouis",
      "name": "St Louis",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 38.6275,
      "lng": -90.1984,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "stockton",
      "name": "Stockton",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 37.9577,
      "lng": -121.291,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "sudbury",
      "name": "Sudbury",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 46.49,
      "lng": -81.01,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "syracuse",
      "name": "Syracuse",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 43.0481,
      "lng": -76.1474,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "tallahassee",
      "name": "Tallahassee",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 30.4383,
      "lng": -84.2807,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "tampa-bay-area",
      "name": "Tampa Bay Area",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 27.9814,
      "lng": -82.4511,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "toledo",
      "name": "Toledo",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.6639,
      "lng": -83.5552,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "topeka-lawrence",
      "name": "Topeka / Lawrence",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 39.0558,
      "lng": -95.689,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "greater-toronto-area",
      "name": "Toronto (GTA)",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 43.6702,
      "lng": -79.3868,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "tucson",
      "name": "Tucson",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 32.2217,
      "lng": -110.926,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "tulsa",
      "name": "Tulsa",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 36.154,
      "lng": -95.9928,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "vancouver",
      "name": "Vancouver",
      "country": "Canada",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 49.2636,
      "lng": -123.139,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "ventura-county",
      "name": "Ventura County",
      "country": "USA",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 34.3705,
      "lng": -119.139,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "victoria",
      "name": "Victoria",
      "country": "Canada",
      "timezone": "Pacific Time (US & Canada)",
      "timezoneOffsetInSeconds": -28800,
      "lat": 48.4286,
      "lng": -123.366,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "washington-dc",
      "name": "Washington DC",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 38.8921,
      "lng": -77.0241,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  [
         {
          "id": "dc-metro",
          "name": "The District",
          "lat": 38.9066,
          "lng": -77.0166
        },
         {
          "id": "northern-virginia",
          "name": "Northern Virginia",
          "lat": 38.8209,
          "lng": -77.291
        },
         {
          "id": "montgomery-county",
          "name": "Montgomery County",
          "lat": 39.0772,
          "lng": -77.1262
        }
      ]
    },
     {
      "id": "westchester-county",
      "name": "Westchester County",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.122,
      "lng": -73.7949,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "wichita",
      "name": "Wichita",
      "country": "USA",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 37.6922,
      "lng": -97.3375,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "wilmington-newark",
      "name": "Wilmington-Newark",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 39.7092,
      "lng": -75.6816,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "windsor",
      "name": "Windsor",
      "country": "Canada",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.2927,
      "lng": -82.9933,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "winnipeg",
      "name": "Winnipeg",
      "country": "Canada",
      "timezone": "Central Time (US & Canada)",
      "timezoneOffsetInSeconds": -21600,
      "lat": 49.8861,
      "lng": -97.1529,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "worcester",
      "name": "Worcester",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 42.2626,
      "lng": -71.8023,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "york-pa",
      "name": "York, PA",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 39.9626,
      "lng": -76.7277,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    },
     {
      "id": "youngstown",
      "name": "Youngstown",
      "country": "USA",
      "timezone": "Eastern Time (US & Canada)",
      "timezoneOffsetInSeconds": -18000,
      "lat": 41.0998,
      "lng": -80.6495,
      "isNowMerchantEnabled": False,
      "isNowCustomerEnabled": False,
      "areas":  []
    }
  ]


if __name__ == '__main__':
    print "Groupon Divisions", len(DIVISIONS)
    print '\n'.join([str((div['id'], div['name'], div['country'], div['timezone'])) for div in DIVISIONS])

