MAIL_LIST_TYPE_NORMAL = 0
MAIL_LIST_TYPE_BLACKLIST = 1
MAIL_LIST_TYPE_WHITELIST = 2
MAIL_LIST_TYPE_ADMINLIST = 3
MAIL_LIST_TYPE_SYSTEMLIST = 4
MAIL_LIST_TYPES = (MAIL_LIST_TYPE_NORMAL, MAIL_LIST_TYPE_BLACKLIST, MAIL_LIST_TYPE_WHITELIST, MAIL_LIST_TYPE_ADMINLIST, MAIL_LIST_TYPE_SYSTEMLIST)

EXEC_CURSOR_START = None
EXEC_CURSOR_END = 'CURSOR_END'
EXEC_MAIL_LIST_LIMIT = 30
NONE_MAIL_ACTUAL_RECIPIENT = "NONE_MAIL_ACTUAL_RECIPIENT"

MAIL_TEMPLATE_TYPE_GENERAL = 'general'
MAIL_TEMPLATE_TYPE_NEWSLETTER = 'newsletter'
MAIL_TEMPLATE_TYPE_REPORT = 'report'
MAIL_TEMPLATE_TYPES = (MAIL_TEMPLATE_TYPE_GENERAL, MAIL_TEMPLATE_TYPE_NEWSLETTER, MAIL_TEMPLATE_TYPE_REPORT)
MAIL_TEMPLATE_TYPE_INIT = MAIL_TEMPLATE_TYPE_GENERAL

LIMIT_EMAIL_CAMPAIGN_PER_RULE = 50

