from django.conf.urls.defaults import patterns

urlpatterns = patterns('',
    (r'^chart$', 'sns.report.views.Chart'),
    (r'^surl/chart/detail$', 'sns.report.views.surlChartDetail'),
    (r'^surl/chart/detail/html5$', 'sns.report.views.surlChartDetailHTML5'),
    (r'^surl/chart/topform$', 'sns.report.views.surlChartTopform'),
    (r'^chartpath/surl/data/clickchart$', 'sns.report.views.surlClickChartData'),
    (r'^chartpath/surl/data/barchart$', 'sns.report.views.surlBarChartData'),
    (r'^url/chart/topform$', 'sns.report.views.urlChartTopform'),
    (r'^user/chart/topform$', 'sns.report.views.userChartTopform'),
    (r'^user/chart/detail$', 'sns.report.views.userChartDetail'),
    (r'^user/chart/detail/html5$', 'sns.report.views.userChartDetailHTML5'),
    (r'^chartpath/user/data/clickchart$', 'sns.report.views.userClickChartData'),
    (r'^chartpath/user/data/channel/piechart$', 'sns.report.views.channelPieChartData'),
    (r'^chartpath/user/data/feed/piechart$', 'sns.report.views.feedPieChartData'),
    (r'^chartpath/user/data/barchart$', 'sns.report.views.userBarChartData'),
    (r'^channel/chart/topform$', 'sns.report.views.channelChartTopform'),
    (r'^channel/chart/detail$', 'sns.report.views.channelChartDetail'),
    (r'^channel/chart/detail/html5$', 'sns.report.views.channelChartDetailHTML5'),
    (r'^chartpath/channel/data/clickchart$', 'sns.report.views.channelClickChartData'),
    (r'^chartpath/channel/data/barchart$', 'sns.report.views.channelBarChartData'),
    (r'^fchannel/chart/topform$', 'sns.report.views.fchannelChartTopform'),
    (r'^fchannel/chart/detail$', 'sns.report.views.fchannelChartDetail'),
    (r'^fchannel/chart/detail/html5$', 'sns.report.views.fchannelChartDetailHTML5'),
    (r'^chartpath/fchannel/data/clickchart$', 'sns.report.views.fchannelClickChartData'),
    (r'^chartpath/fchannel/data/barchart$', 'sns.report.views.fchannelBarChartData'),
    (r'^feed/chart/topform$', 'sns.report.views.feedChartTopform'),
    (r'^feed/chart/detail$', 'sns.report.views.feedChartDetail'),
    (r'^feed/chart/detail/html5$', 'sns.report.views.feedChartDetailHTML5'),
    (r'^chartpath/feed/data/clickchart$', 'sns.report.views.feedClickChartData'),
    (r'^chartpath/feed/data/barchart$', 'sns.report.views.feedBarChartData'),
    
    (r'^campaign/chart/topform$','sns.report.views.campaignChartTopform'),
    (r'^campaign/chart/detail$', 'sns.report.views.campaignChartDetail'),
    (r'^campaign/chart/detail/html5$', 'sns.report.views.campaignChartDetailHTML5'),
    (r'^chartpath/campaign/data/clickchart$', 'sns.report.views.campaignClickChartData'),
    (r'^chartpath/campaign/data/barchart$', 'sns.report.views.campaignBarChartData'),
        
    (r'^chart/blank$', 'sns.report.views.blankDetail'),
    (r'^clickranking$', 'sns.report.views.click_ranking'),
    (r'^clickranking/hour$', 'sns.report.views.click_ranking_hour'),
    (r'^clickranking/today$', 'sns.report.views.click_ranking_today'),
    (r'^clickranking/lifetime$', 'sns.report.views.click_ranking_life_time'),
    (r'^clickranking/week$', 'sns.report.views.click_ranking_week'),
    (r'^clickranking/month$', 'sns.report.views.click_ranking_month'),
    (r'^postfailurelist$', 'sns.report.views.post_failure'),
    (r'^postfailurelist/all$', 'sns.report.views.post_failure_list_all'),
    (r'^postfailurelist/channel$', 'sns.report.views.post_failure_list_channel'),
    (r'^postfailurelist/fchannel$', 'sns.report.views.post_failure_list_fchannel'),
    (r'^postfailurelist/article$', 'sns.report.views.post_failure_list_article'),
    (r'^postfailurelist/feed$', 'sns.report.views.post_failure_list_feed'),
    (r'^postfailurelist/campaign$', 'sns.report.views.post_failure_list_campaign'),
    (r'^postfailurelist/channel/topform$', 'sns.report.views.post_failure_topform_channel'),
    (r'^postfailurelist/fchannel/topform$', 'sns.report.views.post_failure_topform_fchannel'),
    (r'^postfailurelist/article/topform$', 'sns.report.views.post_failure_topform_article'),
    (r'^postfailurelist/feed/topform$', 'sns.report.views.post_failure_topform_feed'),
    (r'^postfailurelist/campaign/topform$', 'sns.report.views.post_failure_topform_campaign'),
    (r'^user/info/detail$', 'sns.report.views.userDetailInfo'),
    (r'^user/info/country$', 'sns.report.views.userCountryBarChart'),
    (r'^user/info/referrer$', 'sns.report.views.userReferrerBarChart'),
    (r'^user/info/html5$', 'sns.report.views.userBarChartHTML5'),
    (r'^surl/info/detail$', 'sns.report.views.surlDetailInfo'),
    (r'^surl/info/country$', 'sns.report.views.surlCountryBarChart'),
    (r'^surl/info/referrer$', 'sns.report.views.surlReferrerBarChart'),
    (r'^surl/info/html5$', 'sns.report.views.surlBarChartHTML5'),
    (r'^channel/info/detail$', 'sns.report.views.channelDetailInfo'),
    (r'^channel/info/country$', 'sns.report.views.channelCountryBarChart'),
    (r'^channel/info/referrer$', 'sns.report.views.channelReferrerBarChart'),
    (r'^channel/info/html5$', 'sns.report.views.channelBarChartHTML5'),
    (r'^fchannel/info/detail$', 'sns.report.views.fchannelDetailInfo'),
    (r'^fchannel/info/country$', 'sns.report.views.fchannelCountryBarChart'),
    (r'^fchannel/info/referrer$', 'sns.report.views.fchannelReferrerBarChart'),
    (r'^fchannel/info/html5$', 'sns.report.views.fchannelBarChartHTML5'),
    (r'^feed/info/detail$', 'sns.report.views.feedDetailInfo'),
    (r'^feed/info/country$', 'sns.report.views.feedCountryBarChart'),
    (r'^feed/info/referrer$', 'sns.report.views.feedReferrerBarChart'),
    (r'^feed/info/html5$', 'sns.report.views.feedBarChartHTML5'),
    (r'^campaign/info/detail$', 'sns.report.views.campaignDetailInfo'),
    (r'^campaign/info/country$', 'sns.report.views.campaignCountryBarChart'),
    (r'^campaign/info/referrer$', 'sns.report.views.campaignReferrerBarChart'),
    (r'^campaign/info/html5$', 'sns.report.views.campaignBarChartHTML5'),
    
    (r'^referrer/detail$', 'sns.report.views.referrerDetail'),
    (r'^surl/search$', 'sns.report.api.surlSearch'),
    (r'^chartpath/data$', 'sns.report.views.chart_data'),
    (r'^quickpost/record$', 'sns.report.views.directPostRecord'),
)
