import datetime

EARLIEST_TIME = datetime.datetime(year=1990,month=1,day=1)

MEDIA_TYPE_ALL      = -1
MEDIA_TYPE_NORMAL   = 0
MEDIA_TYPE_VIDEO    = 1
MEDIA_TYPE_IMAGE    = 2
MEDIA_TYPES = (MEDIA_TYPE_ALL, MEDIA_TYPE_NORMAL, MEDIA_TYPE_VIDEO, MEDIA_TYPE_IMAGE)

IMAGE_URL_EXTENSIONS = ['.jpg', '.png', '.gif', ]
FILE_URL_EXTENSIONS = ['.html', '.shtml', '.htm', '.xml', '.css', '.js', '.swf'] + IMAGE_URL_EXTENSIONS

FEED_FETCHER_HISTORY_LIMIT_DEFAULT = 24

AWS_ACCESS_KEY_ID = 'AKIAJGQLKXNEYMNF66CA'
AWS_SECRET_ACCESS_KEY = '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'
AWS_S3_MULTIPART_MIN_SIZE = 5242880

TWITTER_SHORT_URL_LENGTH_KEY = 'twitter_shorturl_length'
TWITTER_SHORT_URL_LENGTH = 25
TWITTER_MSG_LENGTH_LIMIT = 140

FACEBOOK_MSG_LENGTH_LIMIT = 420
FACEBOOK_POST_TYPE_STANDARD = 0
FACEBOOK_POST_TYPE_COMPACT = 1
FACEBOOK_POST_TYPE_QUICK = 2
FACEBOOK_POST_TYPE=(FACEBOOK_POST_TYPE_STANDARD, FACEBOOK_POST_TYPE_COMPACT,FACEBOOK_POST_TYPE_QUICK)

YOUTUBE_API_KEY = 'AI39si6-TNYxlPy0DKw0V19aTUNsYfKNfB5ysYEouVrEYJA8EEXc_uANM4DNNTXeMZVVpxzIhMSbEFXeTPhTdV178YHWvgsZMw'

INSTAGRAM_CLIENT_ID = '60e8d53b35e04831b1d773f2da19724e' 

COOKIE_USER_SESSION = '__utma'


""" Date & Time consts """
UI_DATETIME_FORMAT = "N j, Y P"
COMMON_DATE_FORMAT = "%Y-%m-%d"
COMMON_DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

    
BROWSER_FIREFOX = "Firefox"
BROWSER_CHROME = "Chrome"
BROWSER_IE = "MSIE"
BROWSER_SAFARI = "Safari"
BROWSERS_KNOWN = (BROWSER_CHROME, BROWSER_FIREFOX, BROWSER_IE, BROWSER_SAFARI, )

DEVICE_IPAD = "iPad"
DEVICE_IPHONE = "iPhone"
DEVICE_IPOD = "iPod"
DEVICE_ANDROID = "Android"
DEVICES_IOS = (DEVICE_IPAD, DEVICE_IPHONE, DEVICE_IPOD, )
DEVICES_PHONE = (DEVICE_IPHONE, DEVICE_IPOD, DEVICE_ANDROID)
DEVICES_TABLET = (DEVICE_IPAD, )
DEVICES_KNOWN = tuple(list(DEVICES_IOS) + [DEVICE_ANDROID])

CONTENT_CUTOFF_HOURS = 24 * 3

BACKEND_REQUIRED_MSG = "Please use backend for this operation!"

JSON_HTTP_RESPONSE_FORMAT = "{'success': False, 'data': None}" 
JSON_HTTP_RESPONSE_ATTR_STATE = 'state'
JSON_HTTP_RESPONSE_STATE_SUCCESS = True
JSON_HTTP_RESPONSE_STATE_FAILURE = False
JSON_HTTP_RESPONSE_ATTR_DATA = 'data'
