""" All constants that can be shared across the board go here. """

TWITTER_MSG_LENGTH_LIMIT = 140
FACEBOOK_MSG_LENGTH_LIMIT = 420

FACEBOOK_POST_TYPE_STANDARD = 0
FACEBOOK_POST_TYPE_COMPACT = 1
FACEBOOK_POST_TYPE_QUICK = 2
FACEBOOK_POST_TYPE=(FACEBOOK_POST_TYPE_STANDARD, FACEBOOK_POST_TYPE_COMPACT,FACEBOOK_POST_TYPE_QUICK)

