""" Account Mmgt Actions """
ACTION_YAHOO_LOGIN = 1
ACTION_YAHOO_CHANGE_PASSWORD_BEGIN = 2
ACTION_YAHOO_CHANGE_PASSWORD_END = 3
ACTION_TWITTER_LOGIN = 11
ACTION_TWITTER_CHANGE_PASSWORD_BEGIN = 12
ACTION_TWITTER_CHANGE_PASSWORD_END = 13


""" All Account Types """
ACCT_TYPE_YAHOO = 0
ACCT_TYPE_TWITTER = 1


""" Operation Types """
ACCT_MGMT_OP_LOGIN = 0
ACCT_MGMT_OP_CHANGE_PASSWORD = 1
ACCT_MGMT_OP_DUMP = 2
ACCT_MGMT_OPS = (ACCT_MGMT_OP_LOGIN, ACCT_MGMT_OP_CHANGE_PASSWORD, ACCT_MGMT_OP_DUMP)


""" All Yahoo states """
YAHOO_STATE_INIT = 0
YAHOO_STATE_SUCCESS = 1
YAHOO_STATE_FAILURE = 2
YAHOO_STATE_CAPTCHA = 3
YAHOO_STATE_PASSWORD_CHANGING = 4
YAHOO_STATE_CHOICES = [
   (YAHOO_STATE_INIT, "Init"),
   (YAHOO_STATE_SUCCESS, "Success"),
   (YAHOO_STATE_FAILURE, "Fail"),
   (YAHOO_STATE_CAPTCHA, "Captcha"),
   (YAHOO_STATE_PASSWORD_CHANGING, "Changing Password"),
]


""" All Twitter states """
TWITTER_STATE_INIT = 0
TWITTER_STATE_SUCCESS = 1
TWITTER_STATE_FAILURE = 2
TWITTER_STATE_CAPTCHA = 3
TWITTER_STATE_PASSWORD_CHANGING = 4
TWITTER_STATE_SUSPENDED = 5
TWITTER_STATE_CHOICES = [
   (TWITTER_STATE_INIT, "Init"),
   (TWITTER_STATE_SUCCESS, "Success"),
   (TWITTER_STATE_FAILURE, "Fail"),
   (TWITTER_STATE_CAPTCHA, "Captcha"),
   (TWITTER_STATE_PASSWORD_CHANGING, "Changing Password"),
   (TWITTER_STATE_SUSPENDED, "Suspended"),
]


ALL_DATETIME_ATTRS = (
    'lastLoginTime',
    'lastPasswdChangeTime',
    'tLastLoginTime',
    'tLastPasswdChangeTime',
    'createdTime',
    'modifiedTime',
    )

DEFAULT_DAY_LIMIT = 30


SHARED_LOGGED_INS = ('ch@snsanalytics.com', )


